name: TDNODE
dependencies:
  - pip=19.3.1=py37_0
  - setuptools=42.0.2=py37_0
  - python=3.7.13
  - pip:
    - black==22.3.0
    - matplotlib==3.1.1
    - pandas==1.2.1
    - scikit-learn==0.24.2
    - scipy==1.7.0
    - torch==1.5.1
    - torchdiffeq==0.0.1
    - tqdm==4.41.1
    - prodict==0.8.3
    - pyyaml==6.0
    - tensorboard==2.7.0
    - torch-summary==1.4.5
    - statsmodels==0.13.2
    - shap==0.41.0
    - xgboost==1.6.2
    - lifelines==0.27.2
    - missingno==0.5.1
    - xgbse==0.2.3




